### python for data analysis video

will only be including some code / notes which i did not knew before - got a eureka out of it.    

https://www.youtube.com/playlist?list=PLiC1doDIe9rCYWmH9wIEYEXXaJ4KAi3jc 


List methods 
.count()
.sort()
.reverse()      
these alter the list itself     
use reverse( list ) so that it return a new list if you need it. 

indexing list[4:2:-1] -> starts at 4th ele and goes till 2 but in reverse.      



In [17]:
list1 = [ 'hi' , 'hello' , 'bye' , 'goodbye' , 'goodnight' , 'goodmorning' ]
list2 = list1[4:2:-1]
print(list2)
list2 = list1[2:4:-1]
print(list2)

['goodnight', 'goodbye']
[]


del(list[2]),  .pop() - last item   

list1 = list2.copy() -> can fool you 

In [31]:
import copy  
list1 = [1,2,3]
list2 = ['list' , list1 , 'list']
list3 = list2.copy()         # shallow copy
# list3 = list2[:]           # same
list4 = copy.deepcopy(list2) # import copy module
print(list2)
print(list3)
print(list4)
list1.append(4)
print(list2)
print(list3)
print(list4)


['list', [1, 2, 3], 'list']
['list', [1, 2, 3], 'list']
['list', [1, 2, 3], 'list']
['list', [1, 2, 3, 4], 'list']
['list', [1, 2, 3, 4], 'list']
['list', [1, 2, 3], 'list']


### tuple

immutable sequence of values.       
means you can't change the values in it.        
but you can change the values in the list inside the tuple.

### string
indivual sequence of immutable objects. <BR>
so in methods like .lower() or .upper() it returns a new string, not changing the original one.     eg below.    
```python  
my_string = "Hello world"
print(my_string.upper())
my_string
```

.find() - returns the index of the first occurence of the substring.    
.replace() - replaces the substring with another substring.
.split("-") - splits the string at the delimiter and returns a list.    
multi line string - """ """ or ''' '''      
.strip("xX") - removes the leading and trailing xX from the string.
"".join("string1","string2") - joins the list of strings with the string.    
formatted string = f"{}" - f string.    
```python
name,age = "Alice",10
print(f"Hello, {name}. You are {age} years old.")
```

 


In [33]:
my_string = "Hello world"
print(my_string.replace('world' , 'python'))
my_string

Hello python


'Hello world'

### dictionary
key value pairs.    
dict.items() - returns a list of tuples. both key and value pairs.      

real world data is usually in the form of dictionaries. with column names as keys and values as the data.
'''python
data = {
    "name" : ["Alice","Bob","Charlie"],
    "age" : [10,20,30]
}
```'    
certain data structures like xml, json are converted to dictionaries. convienient to work with.



### set

sets are ordered, mutable, no duplicates collection of immutable objects.       
set1 = {1,2,3,4}        
set2 = {3,4,5,6}        
set1.union(set2) - returns a new set with all the elements of both the sets.    
do not support indexing.        
but has .add() and .remove() methods. "in" , "not in" operators can be used.

.union() , .intersection()
.difference() - elements in set1 but not in set2        
.symmetric_difference() - elements in set1 or set2 but not in both. <br>
.issubset() , .issuperset() , .isdisjoint() - for checking the relationship between the sets.        <br>
set1.update(set2) - updates set1 with the elements of set2. <br>
set1.intersection_update(set2) - updates set1 with the intersection of set1 and set2. <br>


### numpy

arr1 = np.array(list1)      
.shape , .size - shape of the array and size of the array. <br>
.dtype
np.zeros((2,3)) - creates a 2x3 array of zeros. <br>
np.identity(3) - creates a 3x3 identity matrix. <br>
indexing and slicing is possible. <br>

```python
one_d_array = np.array([1,2,3,4,5])
two_d_array = np.array([one_d_array, one_d_array+6])
two_d_array[1,2] # 9
two_d_array[1,1:3] # [8,9]
two_d_array[::-1,::-1] # reverse the array  
```
.reshape() - reshapes the array. <br>
.flatten() - flattens the array. <br> 
np.ravel(a=,order=) - same as flatten but can also do it by column (order=F) <br>

.T = transpose of the array. <br>
.flipud() , .fliplr() - flips the array up down and left right. <br>
.rot90(k=) - rotates the array by 90 degrees k times. <br>
np.roll(a=,shift=) - rolls the array by shift times. <br>
arr1.concatenate(arr2,axis=,out=) - concatenates the arrays, axis=0 for vertical, axis=1 for horizontal <br>
```python
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2),axis=0)
np.concatenate((arr1,arr2),axis=1)
arr1.concatenate(arr2,axis=0)
```

math operations are elemeent wise and faster, memory efficient in numpy <br>

two_d_array.sum(axis=0) - sum of the columns <br>
two_d_array.sum(axis=1) - sum of the rows <br>
two_d_array.mean(axis=0)
.std() , .var() - standard deviation and variance <br>
.min() , .max() - min and max <br>
.argmin() , .argmax() - index of min and max <br>
.argsort() - returns the indices of the sorted array <br>
np.where(condition) - returns the indices of the elements which satisfy the condition <br>

np.random.rand(2,3) - random numbers between 0 and 1 , returns a 2x3 array <br>
np.random.randn(2,3) - random numbers from normal distribution <br>
np.random.randint(1,10,(2,3)) - random integers between 1 and 10 , returns a 2x3 array <br>

In [38]:
#%pip install numpy
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(np.concatenate((arr1,arr2),axis=0)) # axis=0 mean concatenate column wise
print(np.concatenate((arr1,arr2),axis=1)) # axis=1 mean concatenate row wise
# arr1.concatenate(arr2,axis=0) # error 
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]]


In [61]:
# %pip install pandas
import pandas as pd

### pandas
#### pandas series
one dimensional labeled array. <br>
s = pd.Series([1,2,3,4],index=["a","b","c","d"]) <br>
dict= {"a":1,"b":2,"c":3,"d":4} <br>
s = pd.Series(dict) <br>

```python
my_dict = {
    "name" : ["Alice","Bob","Charlie"],
    "age" : np.array([10,20,30]),
    'weight' : pd.Series([20,30,40],index=["A","B","C"])
    'height' : pd.Series([20,30,40],index=["al","bo","ch"]) # error, index shpuld be same and complusory
    'sibilings' : 1,
    'gender' : "F"
}
df = pd.DataFrame(my_dict)
```
df["name"] , df.name - both are same. <br>
del df["name"] - deletes the column. <br>

df.loc["A"] , df.iloc[0] - both in our case is same. but loc is label based and iloc is index based. so if row shuffled, iloc will give the 1st row, but loc will give the row with label A. <br>

df.loc["A":"B","name":"age"] - slicing the dataframe. <br>
df.iloc[0:2,0:2] - slicing the dataframe. <br>

logical indexing -
bool_index = df["age"] > 20 <br>
df[bool_index]  <br>


In [59]:
dict= {"a":1,"b":2,"c":3,"d":4} 
s = pd.Series(dict) 
print(s)
my_dict = {
    "name" : ["Alice","Bob","Charlie"],
    "age" : np.array([10,20,30]),
    'weight' : pd.Series([20,30,40],index=["A","B","C"]),
    'height' : [1,2,3],
    'no' : pd.Series([1,2,3],index=["A","B","C"]), # index should be same and complusory
    'sibilings' : 1,
}
df = pd.DataFrame(my_dict)
print(df)

a    1
b    2
c    3
d    4
dtype: int64
      name  age  weight  height  no  sibilings
A    Alice   10      20       1   1          1
B      Bob   20      30       2   2          1
C  Charlie   30      40       3   3          1


import os <br>
os.getcwd() - get the current working directory <br>
os.chdir(/kaggle/) <br>
os.listdir(/kaggle/input/) - list the files in the directory <br>

pd.read_table("file.txt",sep="") - 
pd.read_csv("file.csv") -   
pd.read_excel("file.xlsx", sheet="sheet1")      
pd.read_sql("select * from table",connection) - reads the sql query from the database. <br>
pd.read_clipboard() - reads the data from the clipboard. <br>
pd.read_html("url") - reads the html table from the url. needs beautifulsoup4 and html5lib. <br>
draft.to_csv("file.csv") - writes the dataframe to the csv file. <br>


make -ve numbers zero of some sort of transformation - df[df<0] = 0 <br>

In [77]:
my_data = np.random.uniform(-1,1,(3,3)) # 5x5 matrix with random values between -1 and 1
for i,data in enumerate(my_data.flatten()): # flatten() convert 2d array to 1d array, enumerate() return index and value
    if data < 0:
        print(i,data, sep=" : ")
        my_data.flat[i] = 0 # flat is a 1d array of my_data, so we can change value, flat is a view of my_data
print(my_data)

0 : -0.33621157217989395
4 : -0.8030256050833602
5 : -0.9782935965408843
6 : -0.1883420264137099
7 : -0.8758897202186617
8 : -0.2655239816925956
[[0.         0.63787072 0.21416869]
 [0.97081354 0.         0.        ]
 [0.         0.         0.        ]]


In [81]:
my_data = np.random.uniform(-1,1,(3,3))
np.where(my_data < 0, 0, my_data) # if data is less than 0 then replace with 0 else keep same
# substantailly faster than above loopinng method

array([[0.        , 0.90972128, 0.76577167],
       [0.        , 0.48328731, 0.80300994],
       [0.09672036, 0.        , 0.        ]])

```python
def sum(*args):
    print(type(args))
    return sum(args)
sum(1,2,3,4)

def keywordargs(**kwargs): # keyword arguments - 
    print(type(kwargs))
    print(kwargs.keys())
    print(kwargs.values())
    return sum(kwargs.values())
keywordargs(a=1,b=2,c=3) 

(lambda x, y : x + y) # can be used along with map, filter, reduce

map(lambda x : x**2, [1,2,3,4])
filter(lambda x : x%2==0, [1,2,3,4])
reduce(lambda x,y : x+y, [1,2,3,4])
df["age"].apply(lambda x : x**2) # apply the lambda function to the series

# eg with increase complexity

map(lambda x : x**2, df["age"]) # apply the lambda function to the series returns a map object




```

<function __main__.<lambda>(x, y)>

#### list comprehension
[expression for item in iterable if condition] <br>
```python
squares = [x**2 for x in range(10)]
squares = [x**2 for x in range(10) if x%2==0]
comboned =[x+y for x in "life" for y in "sucks"]
```
#### dictionary comprehension
{key:value for item in iterable if condition} <br>
```python
squares = {x:x**2 for x in range(10) if x%2==0}
comboned = {x:y for x in "life" for y in "sucks"}
```
zip() - combines the two lists into a list of tuples. <br>
```python
zipped = zip(list1,list2) # returns tuple made elements wise
my_dict = {key:value for key,value in zipped}
unzipped = zip(*zipped)
list(unzipped)
```


In [92]:
comboned = {x:y for x in ["life"," ",";"] for y in ["suck"]}
comboned

{'life': 'suck', ' ': 'suck', ';': 'suck'}

### Data Exploration and Cleaning
[Kaggle Notebook](https://www.kaggle.com/code/saranshkathal/python-for-data-14-data-exploration-and-cleaning/edit) <br>

Exploring the variables:
    use .shape(), .dtypes(), .describe(), .info() 
Qs : 
    Do I Need All of the Variables? 
        Can i drop some columns ? variables ?
        Look at all variable closely.
        Is there a Pattern?
        
    Should I Transform Any Variables?
        pd.Categorical(), pd.to_datetime()
        use .unique(), .describe() after transformation
        use comprehensions, lambda functions, map, filter, reduce for transformation

    Are there NA Values, Outliers or Other Strange Values?
        .isna(), .isnull(), .fillna(), .dropna()
        .drop_duplicates()
        .value_counts()
        .plot(kind="bar"), .plot(kind="hist"), variable.hist(col=,figsize=,bins=) , variable.boxplot(), variable.plot(kind="scatter",x=,y=) 
        can fill mean , meadian after checking for normal distribution
        can use to find index and fill values using np.where(condition,fill_value_true,fill_value_false)

    Should I Create New Variables?
        Creating a new variable can be as simple as taking one variable and adding, multiplying or dividing by another
        



 .describe() on Categoical data <br>
```python
categorical = titanic_train.dtypes[titanic_train.dtypes == "object"].index
print(categorical)

titanic_train[categorical].describe()
```

Filling in the missing values - 
there is often a no right way to fill in the missing values it a matter of judgement and having experience in your domain. <br>
Similar to NA values, there's no single cure for outliers. You can keep them, delete them or transform them in some way to try to reduce their impact. Even if you decide to keep outliers unchanged it is still worth identifying them since they can have disproportionately large influence on your results

#### 


```python
new_survive = pd.Categorical(df["survived"]) #converts the column to categorical.
new_survive = df["survived"].rename_categories(["Died","Survived"])  # renames the categories. <br>
new_survive.describe() 
```

#### Working with Text Data
pandas has a lot of built-in methods for working with text data. <br>
pd.Series() - can be used to convert the list to series. <br>
then        
> comments.str.lower() or comments[0].lower() <br> 
similarily .lower(), .upper(), .str.len(), .strip("[ ]"), .str.cat(), .str.split(), 
can make a logica expressions / indexing  using .contains("virat|kohli"), .startswith("virat"), .endswith("kohli") <br> 

.contains(".ill") - returns the rows which contains the string "ill" <br>
[Tt] - returns the rows which contains the string "T" or "t" <br>
etc. 

using re or use any other from online.


#### working with numerical data
Very Good for knowing some basic steps and why - scaling / substracting mean, skewed data transformations - log and sqrt , correlation variables and what to do with them and lastly imputation techniques. and code for all. <br>
[Youtube](https://www.youtube.com/watch?v=Y1mXf0rXm04&list=PLiC1doDIe9rCYWmH9wIEYEXXaJ4KAi3jc&index=16)
[| Much better and faster read this kaggle nb](https://www.kaggle.com/code/hamelg/python-for-data-16-preparing-numeric-data)


tranformations on numeric data - 
```python
(data+1).apply(np.log) # log transformation or use np.log1p(data) , 1 + in  log1p is to avoid log(0) error amnd negative values
data.apply(np.sqrt) # sqrt transformation
data.apply(lambda x : x**0.33) # cube root transformation
```
##### correlation
correlation is a measure of how two variables change together. and typically due to some underlying relationship. (but causation v/s correlation) <br>

.corr() , scatter_matrix() , sns.pairplot() <br>
scatter plot is a good way to look at data and sopt interesting relationships. <br>

high correlation can be a problem in some models and can interfere and skrew up results. <br>

leave them be, drop one of the variables, combine the variables, transform the variables. <br>
dimentionality reduction (PCA) - can be used to reduce the number of variables. <br>




#### Imputation
use np.where(condition,fill_value_true,fill_value_false) <br>
Imputer() - from sklearn.preprocessing  - strategy = "mean" , "median" , "most_frequent" <br>
k nearest neighbours - from sklearn.impute - KNNImputer() - but it significantly increases the complexity time as it itself is a predictive model, and may not increase the yeaild significantly. <br>
IterativeImputer() - from sklearn.impute - uses a predictive model to fill in the missing values. <br>

#### Scaling
scaling is important because many machine learning algorithms don't perform well when the input numerical variables have different scales. <br>
StandardScaler() - from sklearn.preprocessing - scales the data so that it has a mean of 0 and a standard deviation of 1. <br>
MinMaxScaler() - scales the data so that all the values are between 0 and 1. <br>
RobustScaler() - scales the data so that it is robust to outliers. <br>

#### dealing with dates
df = pd.read_csv("file.csv",parse_dates=["date", 0]) - state the column name or number which has the date. <br>

od pd.to_datetime(data,format="%H:%M:%S %Y-%m-%d") - the format is the one in which the date data is present. <br>
https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html


we can extract the year, month, day, weekday, etc. <br> 
df["date"].dt.year , df["date"].dt.month , df["date"].dt.day , df["date"].dt.weekday , df["date"].dt.quarter <br>

print(dates.iloc[0] - dates.iloc[1]) - gives the difference in the dates. <br>

#### merge and join
pd.merge(df1,df2,on=["column_name", "col_2"],how="") - merges the two dataframes on the column name. <br>
how = "inner" -> intersection, "outer" -> union, "left" -> left join, "right" -> right join <br>